font = CurrentFont()

#greek
#selectedGlyphs = ['dieresistonoscomb', 'gamma', 'upsilontonos', 'Xi', 'Gamma', 'Upsilontonos', 'delta', 'chi', 'omega', 'Zeta', 'tonoscomb', 'omicrontonos', 'tonos.case', 'iotatonos', 'gr:question', 'tonos', 'alpha', 'alphatonos', 'Omicron', 'Mu', 'Theta', 'Delta', 'theta', 'psi', 'Alphatonos', 'Psi', 'upsilon', 'rho', 'kaisymbol', 'Iotadieresis', 'sigma', 'increment', 'upsilondieresistonos', 'Omega', 'Phi', 'Tau', 'dieresistonos', 'etatonos', 'finalsigma', 'beta', 'iota', 'Omicrontonos', 'epsilon', 'omegatonos', 'anoteleia', 'Rho', 'upsilondieresis', 'Chi', 'iotadieresis', 'Beta', 'Pi', 'Upsilon', 'Etatonos', 'Iota', 'eta', 'Eta', 'omicron', 'epsilontonos', 'Epsilontonos', 'Iotatonos', 'iotadieresistonos', 'Upsilondieresis', 'Kappa', 'Alpha', 'zeta', 'Kaisymbol', 'lambda', 'phi', 'Sigma', 'tau', 'Epsilon', 'Omegatonos', 'Lambda', 'mu', 'numeralsign', 'pi', 'ohm', 'xi', 'kappa', 'lownumeralsign', 'Nu', 'nu']

#math
#selectedGlyphs = ['approxequal', 'divide', 'greater', 'greaterequal', 'less', 'lessequal', 'logicalnot', 'minus', 'multiply', 'notequal', 'plus', 'plusminus', 'divide', 'equal', 'less']

#accents & combs
#selectedGlyphs = ['acute', 'acutecomb', 'acutecomb.case', 'acutecombstack.case', 'breve', 'breve.cyr.case', 'breveacutecomb', 'breveacutecomb.case', 'brevebelowcomb', 'brevebelowcomb.case', 'brevecomb', 'brevecomb.case', 'brevecombstack.case', 'brevegravecomb', 'brevegravecomb.case', 'brevehookabovecomb', 'brevehookabovecomb.case', 'breveinvertedcomb', 'breveinvertedcomb.case', 'brevetildecomb', 'brevetildecomb.case', 'caron', 'caroncomb', 'caroncomb.case', 'cedilla', 'cedillacomb', 'cedillacomb.case', 'circumflex', 'circumflexacutecomb', 'circumflexacutecomb.case', 'circumflexcomb', 'circumflexcomb.case', 'circumflexcombstack.case', 'circumflexgravecomb', 'circumflexgravecomb.case', 'circumflexhookabovecomb', 'circumflexhookabovecomb.case', 'circumflextildecomb', 'circumflextildecomb.case', 'commaaccentcomb', 'commaaccentcomb.case', 'dblgravecomb', 'dblgravecomb.case', 'dieresis', 'dieresisbelowcomb', 'dieresisbelowcomb.case', 'dieresiscomb', 'dieresiscomb.case', 'dieresiscombstack.case', 'dotaccent', 'dotaccentcomb', 'dotaccentcomb.case', 'dotaccentcombstack.case', 'dotbelowcomb', 'dotbelowcomb.case', 'grave', 'gravecomb', 'gravecomb.case', 'gravecombstack.case', 'hookabovecomb', 'hookabovecomb.case', 'hookabovecombstack.case', 'horncomb', 'horncomb.case', 'hungarumlaut', 'hungarumlautcomb', 'hungarumlautcomb.case', 'macron', 'macronbelowcomb', 'macronbelowcomb.case', 'macroncomb', 'macroncomb.case', 'macroncombstack.case', 'ogonek', 'ogonekcomb', 'ogonekcomb.case', 'ring', 'ringcomb', 'ringcomb.case', 'tilde', 'tildecomb', 'tildecomb.case', 'tildecombstack.case']

#diagonal 001s
#selectedGlyphs = [ 'numbersign', 'slash', 'less', 'greater', 'A', 'K', 'R', 'V', 'W', 'X', 'Y', 'backslash', 'asciicircum', 'grave', 'f', 'j', 'k', 'r', 't', 'v', 'w', 'x', 'y', 'asciitilde', 'yen', 'registered', 'AE', 'germandbls', 'gravecomb', 'acutecomb', 'circumflexcomb', 'tildecomb', 'brevecomb', 'hungarumlautcomb', 'caroncomb', 'ogonekcomb', 'jdotless', 'flig2', 'tlig', ]

#rotated glyphs
#selectedGlyphs = ['B', 'C', 'D', 'G', 'O', 'P', 'Q', 'R', 'S', 'U', 'a', 'b', 'c', 'd', 'e', 'g', 'o', 'p', 'q', 's', 'u', 'dollar', 'dollar.rvrn', 'cent.rvrn', 'zero', 'two', 'three', 'five', 'six', 'eight', 'nine', 'zero.prop', 'two.prop', 'three.prop', 'five.prop', 'six.prop', 'eight.prop', 'nine.prop', 'percent', 'perthousand', 'cent', 'ordfeminine', 'ordmasculine', 'quotesingle', 'quotedbl', 'questiondown', 'question', 'slash', 'asterisk', 'quoteleft', 'quoteright', 'quotesinglbase', 'quotedblleft', 'quotedblright', 'quotedblbase', 'zerosuperior', 'onesuperior', 'twosuperior', 'threesuperior', 'foursuperior', 'onequarter', 'onehalf', 'threequarters', 'fraction' ]


#SLANT

selectedGlyphs = [ 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'Germandbls', 'germandbls', 'paragraph', 'dollar', 'sterling', 'yen', 'numbersign', 'Euro', 'franc', 'lira', 'naira', 'peseta', 'won', 'dong', 'rupeeIndian', 'liraTurkish', 'manat', 'ruble', 'numero', 'commercialMinusSign', 'florin', 'coloncurrency', 'uni20AD', 'uni20B1', 'uni20B2', 'uni20B5', 'hryvnia', 'tenge', 'dollar.rvrn', 'cent.rvrn', 'coloncurrency.rvrn', 'naira.rvrn', 'won.rvrn', 'uni20B1.rvrn', 'uni20B2.rvrn', 'uni20B5.rvrn', 'hryvnia.rvrn', 'zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'zero.prop', 'one.prop', 'two.prop', 'three.prop', 'four.prop', 'five.prop', 'six.prop', 'seven.prop', 'eight.prop', 'nine.prop', 'cent', 'ordfeminine', 'ordmasculine', 'quotesingle', 'quotedbl', 'ampersand', 'questiondown', 'question', 'exclamdown', 'exclam', 'parenleft', 'slash', 'parenright', 'bracketleft', 'backslash', 'bracketright', 'braceleft', 'bar', 'braceright', 'brokenbar', 'asterisk', 'comma', 'periodcentered', 'quoteleft', 'quoteright', 'quotesinglbase', 'quotedblleft', 'quotedblright', 'quotedblbase', 'guilsinglleft', 'guilsinglright', 'guillemotleft', 'guillemotright', 'underscore', 'hyphen', 'hyphentwo', 'endash', 'emdash', 'softhyphen', 'trademark', 'asciicircum', 'asciitilde', 'zerosuperior', 'onesuperior', 'twosuperior', 'threesuperior', 'foursuperior', 'fraction', 'divisionslash', 'primemod', 'doubleprimemod', 'apostrophemod', 'horizontalbar', 'minute', 'second', 'leftanglebracket', 'rightanglebracket', ]
selectedGlyphs += [ 'gravecomb', 'acutecomb', 'circumflexcomb', 'tildecomb', 'macroncomb', 'brevecomb', 'dotaccentcomb', 'dieresiscomb', 'hookabovecomb', 'ringcomb', 'hungarumlautcomb', 'caroncomb', 'breveinvertedcomb', 'dblgravecomb', 'horncomb', 'dotbelowcomb', 'dieresisbelowcomb', 'commaaccentcomb', 'cedillacomb', 'ogonekcomb', 'brevebelowcomb', 'macronbelowcomb', 'commaaccentturnedcomb', 'gravecomb-stack', 'acutecomb-stack', 'dieresiscomb-stack', 'macroncomb-stack', 'circumflexcomb-stack', 'caroncomb-stack', 'brevecomb-stack', 'dotaccentcomb-stack', 'ringcomb-stack', 'tildecomb-stack', 'hungarumlautcomb-stack', 'hookabovecomb-stack', 'breveinvertedcomb.stack', 'dblgravecomb-stack', ]
selectedGlyphs += [ 'gravecomb.case', 'acutecomb.case', 'dieresiscomb.case', 'macroncomb.case', 'cedillacomb.case', 'circumflexcomb.case', 'caroncomb.case', 'brevecomb.case', 'dotaccentcomb.case', 'ringcomb.case', 'ogonekcomb.case', 'tildecomb.case', 'hungarumlautcomb.case', 'hookabovecomb.case', 'breveinvertedcomb.case', 'dblgravecomb.case', 'horncomb.case', 'dotbelowcomb.case', 'dieresisbelowcomb.case', 'commaaccentcomb.case', 'brevebelowcomb.case', 'macronbelowcomb.case', 'gravecombstack.case', 'acutecombstack.case', 'dieresiscombstack.case', 'macroncombstack.case', 'circumflexcombstack.case', 'brevecombstack.case', 'dotaccentcombstack.case', 'tildecombstack.case', 'hookabovecombstack.case', ]
selectedGlyphs += [ 'gravecomb-stack.case', 'acutecomb-stack.case', 'dieresiscomb-stack.case', 'macroncomb-stack.case', 'circumflexcomb-stack.case', 'caroncomb-stack.case', 'brevecomb-stack.case', 'dotaccentcomb-stack.case', 'ringcomb-stack.case', 'tildecomb-stack.case', 'hungarumlautcomb-stack.case', 'hookcomb-stack.case', 'breveinvertedcomb-stack.case', 'dblgravecomb-stack.case', ]
selectedGlyphs += [ 'AE', 'Thorn', 'ae', 'eth', 'thorn', 'kgreenlandic', 'OE', 'oe', 'idotless', 'jdotless', 'Schwa', 'schwa', ]
selectedGlyphs += [ 'caroncomb.alt', 'diagonalbarO', 'diagonalbarl', 'diagonalbaro', 'engtail', 'horizontalbarH', 'horizontalbarlc', 'diagonalbarL', 'diagonalbarO.rvrn', 'diagonalbaro.rvrn', ]
selectedGlyphs += [ 'Gamma', 'Delta', 'Theta', 'Lambda', 'Xi', 'Pi', 'Sigma', 'Phi', 'Psi', 'Omega', 'Kaisymbol', 'alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta', 'iota', 'kappa', 'lambda', 'mu', 'xi', 'pi', 'rho', 'finalsigma', 'sigma', 'tau', 'upsilon', 'phi', 'chi', 'psi', 'omega', 'kaisymbol', 'numeralsign', 'lownumeralsign', 'tonoscomb', 'tonoscomb.case', ] # 'dieresistonoscomb', 'dieresistonoscomb.case',
selectedGlyphs += [ 'Dje', 'Ieukran', 'Lje', 'Nje', 'Tshe', 'Dzhe', 'Be', 'De', 'Zhe', 'Ze', 'Icyr', 'Ka', 'El', 'Ucyr', 'Tse', 'Che', 'Sha', 'Hard', 'Soft', 'Ecyr', 'Ya', 'Gheup', 'Kaverticalstrokecyr', 'Kabashkircyr', 'Cheverticalstroke-cy', 'Shha', 'De.bgr', 'Zhe.bgr', 'be', 've', 'ghe', 'de', 'zhe', 'ze', 'icyr', 'ka', 'el', 'em', 'en', 'pe', 'te', 'tse', 'che', 'sha', 'hard', 'soft', 'ecyr', 'ya', 'ieukran', 'lje', 'nje', 'dzhe', 'gheup', 'kaverticalstrokecyr', 'kabashkircyr', 'ustraight', 'cheverticalstroke-cy', 've.bgr', 'ghe.bgr', 'zhe.bgr', 'ze.bgr', 'el.bgr', 'sha.bgr', 'hard.bgr', 'soft.bgr', 'be.locl', 'breve.cyrcomb.case', 'breve.cyrcomb', 'Cy-descendercomb.case', 'cy-descendercomb', 'U-stroke', 'u-stroke', 'Obarcyr-stroke', 'Hacyr-stroke', 'obarcyr-stroke', 'hacyr-stroke', 'Yu-dash.case', 'yu-dash', ]



for g in selectedGlyphs:
    font[g].selected = True
    #font[g].width = 536

print (selectedGlyphs)